environment:
  hostname: ponglehub.co.uk

nginx-ingress:
  controller:
    service:
      type: NodePort
      nodePorts:
        http: 30080
        https: 30443
        tcp:
          32222: 32222
    extraArgs:
      default-ssl-certificate: infra/wildcard-cert
  tcp:
    32222: infra/git-server:2222

certManager:
  httpIssuer: false

metrics-server:
  args:
    - --kubelet-insecure-tls
    - --kubelet-preferred-address-types=InternalIP

verdaccio:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 0m
      cert-manager.io/cluster-issuer: selfsigning-issuer
    hosts:
    - npm.ponglehub.co.uk
    tls:
    - hosts:
      - npm.ponglehub.co.uk
      secretName: npm-cert

git:
  base:
    user: git
    id_rsapub: base-encoded
  hostname: git.ponglehub.co.uk

elasticsearch:
  antiAffinity: "soft"
  esJavaOpts: "-Xmx128m -Xms128m"
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "512M"
  persistence:
    annotations:
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 100M
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 0m
      cert-manager.io/cluster-issuer: selfsigning-issuer
    hosts:
    - elastic.ponglehub.co.uk
    tls:
    - hosts:
      - elastic.ponglehub.co.uk
      secretName: elastic-cert

kibana:
  resources:
    requests:
      cpu: "500m"
      memory: "512M"
    limits:
      cpu: "500m"
      memory: "512M"
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 0m
      cert-manager.io/cluster-issuer: selfsigning-issuer
    hosts:
    - kibana.ponglehub.co.uk
    tls:
    - hosts:
      - kibana.ponglehub.co.uk
      secretName: kibana-cert
