environment:
  hostname: ponglehub.co.uk

nginx-ingress:
  controller:
    service:
      type: NodePort
      nodePorts:
        http: 30080
        https: 30443
        tcp:
          32222: 32222
    extraArgs:
      default-ssl-certificate: infra/wildcard-cert
  tcp:
    32222: infra/git-server:2222

metrics-server:
  args:
    - --kubelet-insecure-tls
    - --kubelet-preferred-address-types=InternalIP

secrets:
  admin:
    username: admin
    # password:

grafana:
  admin:
    existingSecret: grafana-creds
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - id: prometheus
        name: Prometheus
        type: prometheus
        url: http://metrics-prometheus-server
        access: proxy
        isDefault: true
      - id: loki
        name: Loki
        type: loki
        url: http://metrics-loki:3100
        access: proxy
        jsonData:
          derivedFields:
          - matcherRegex: "level=(\\w+)"
            name: level
            url: ""
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 0m
      cert-manager.io/cluster-issuer: selfsigning-issuer
    hosts:
    - grafana.ponglehub.co.uk
    tls:
    - hosts:
      - grafana.ponglehub.co.uk
      secretName: grafana-cert

verdaccio:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 0m
      cert-manager.io/cluster-issuer: selfsigning-issuer
    hosts:
    - npm.ponglehub.co.uk
    tls:
    - hosts:
      - npm.ponglehub.co.uk
      secretName: npm-cert

git:
  base:
    user: git
    id_rsapub: base-encoded
  hostname: git.ponglehub.co.uk