verdaccio:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 0m
      cert-manager.io/cluster-issuer: selfsigning-issuer
    hosts:
    - npm.ponglehub.co.uk
    tls:
    - hosts:
      - npm.ponglehub.co.uk
      secretName: npm-cert

git:
  base:
    user: git
    id_rsapub: base-encoded
  hostname: git.ponglehub.co.uk