apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.issuer }}
    nginx.ingress.kubernetes.io/proxy-body-size: 0m
  labels:
    app: git-repo
  name: git
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: git-repo
          servicePort: 22
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName: git-cert
