apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: wildcard-cert
spec:
  secretName: wildcard-cert
  dnsNames:
  - "*.{{ .Values.environment.hostname }}"
  issuerRef:
    name: self-signed
    kind: ClusterIssuer